apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  clusterIP: None
  ports:
  - name: rsync
    port: {{ $.Values.port }}
    protocol: TCP
    targetPort: {{ $.Values.port }}
  selector:
    app: {{ $.Chart.Name }}
  type: ClusterIP
